version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nftgo/web:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:3000/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 10s
      timeout: 5s
      retries: 10
