import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import {Header} from "@/shared/ui/header";
import {BottomNav} from "@/feature/bottom-nav";
import Script from "next/script";
import {AppProviders} from "@/app/AppProviders";

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
    display: "swap",
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    const imageUrls: string[] = [
        '/tonCoin.svg',
        '/file.svg',
        '/globe.svg',
        '/logo.svg',
        '/next.svg',
        '/nft-1.png',
        '/tonCoin.svg',
        '/tonkeeper.svg',
        '/vercel.svg',
        '/window.svg',
        '/bottomNav/friends.svg',
        '/bottomNav/market.svg',
        '/bottomNav/profile.svg',
        '/bottomNav/rocket.svg',
        '/bottomNav/top.svg',
        '/friends/nftGoLogo.png',
        '/friends/ticket.png',
        '/profile/lock.svg',
        '/profile/nft-2.svg',
        '/profile/nftGoLogo.svg',
        '/rocket/deposit-2.svg',
        '/rocket/rocket.png',
        '/rocket/wifi.png'
    ];

    return (
        <html lang="en" suppressHydrationWarning>
        <head>
            {imageUrls.map((url, index) => (
                <link key={index} rel="preload" href={url} as="image"/>
            ))}
            <Script
                src="https://telegram.org/js/telegram-web-app.js"
                strategy="beforeInteractive"
            />
        </head>
        <body
            className={`${montserrat.variable} antialiased bg-[#150f27]`}
        >
        <AppProviders>
                <Header/>
                <div className={'bg-[#150f27] min-h-screen text-white px-[15px] mx-auto relative'}>
                    {children}
                </div>
                <BottomNav/>
        </AppProviders>
        </body>
        </html>
    );
}
