name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -euo pipefail
            cd /home/site/nftgo
            git pull origin main

            if command -v docker compose >/dev/null 2>&1; then
              docker compose build --pull
              docker compose down --remove-orphans -v
              docker network prune -f || true
              docker compose up -d
            else
              docker-compose build --pull
              docker-compose down --remove-orphans -v
              docker network prune -f || true
              docker-compose up -d
            fi
